services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: test

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    ports:
      - "3000:3000"
